### ISSUE TITLE
iOS夯实：ARC时代的内存管理

### ISSUE THREAD

**Issue by fei-sheng** [100mango/zen#10]
在 viewDidLoad 中创建 timer 并用作为 strong 属性，代码如下：
NSTimer *time = [NSTimer timerWithTimeInterval:3.0 target:self selector:@selector(timeEnd:) userInfo:@"userinfo" repeats:NO];
[[NSRunLoop currentRunLoop] addTimer:time forMode:NSDefaultRunLoopMode];
 self.mytimer = time;
运行在 iOS9.2 模拟器上时，dealloc 方法是会调用的，不像你上面所说的强引用问题。
你可以再看看

**Comment by 100mango** [comment]
这是因为“repeats:NO”。你试试repeats:YES的情况。然后我更新了NSTimer一节，加入了更详细的介绍，应该会更清晰一点。希望对你有帮主。
