### ISSUE TITLE
这是一个关于DispatchWallTime的使用问题？如果你能帮助我，真的很感谢

### ISSUE THREAD

**Issue by baobao57** [100mango/zen#12]
let sourceWallTimer = DispatchSource.makeTimerSource(queue: DispatchQueue.global())
        let wallTimeInterval = DispatchTimeInterval.seconds(1)
        
        let walltime = DispatchWallTime.now() + wallTimeInterval
        print("time-now : \(DispatchWallTime.now())")
        print("walltime : \(walltime)")
        sourceWallTimer.scheduleRepeating(wallDeadline: walltime, interval: wallTimeInterval)
        sourceWallTimer.setEventHandler {
            NSLog("定时器运行：--walltime")
        }
        
        if #available(iOS 10.0, *) {
            sourceWallTimer.activate()
        } else {
            // Fallback on earlier versions
            sourceWallTimer.resume()
        }      
        
 我运行的结果是这样的，我发现walltime
   time-now : DispatchWallTime(rawValue: 16968580581812839616)
   walltime :   DispatchWallTime(rawValue: 16968580580812844616)
   1分钟左右之后的再次运行
   time-now : DispatchWallTime(rawValue: 16968580437033322616)
   walltime :   DispatchWallTime(rawValue: 16968580436033328616)
  ==》从这个参数上来看walltime可能是从现在到未来的最大值之间的一个 时间长度值
这个值看起来让我觉得并没有设么规律
可能由于模拟器的时间和现实的时间并不一致，大体的时间是不正确的。   
但是这个walltime的使用，使得定时器并不能运行，如果使用DispatchTime的初始化时间是没有问题的。

**Comment by 100mango** [comment]
不是很明白你说的这个是什么问题。你可以参考一下SwiftTimer的源代码，按照SwiftTimer的代码模式来使用就好。

**Comment by baobao57** [comment]
我只是在使用的时候，scheduleRepeating这个方法有好多个不同的参数配置。  
其中就包括
![像这个图片一样](https://github.com/baobao57/storeResource/blob/master/dispatchWallTime.png?raw=true)
这里的DispatchWallTime 应该也可以用到timer里吧，  但是我使用他的时候，他却不会执行timer。
请问你对DispatchWallTime使用过么？    ios10   swift3.0

**Comment by 100mango** [comment]
我觉得有可能原因是你是在Playground上面运行的。Playground执行完一遍就结束进程了。你需要在Playground加上一句：PlaygroundPage.current.needsIndefiniteExecution = true

**Comment by baobao57** [comment]
原因我找到了。是因为我初始化timer的时候，没有初始化成一个全局变量，当方法执行过后，这个timer就被销毁了。也就不会调用**定时器**。
DispatchTime & dispatchWallTime 使用并无区别，只不过根据网上的说法是一个是相对时间，一个代表的是绝对时间。  就是dispatchTime可能会在特殊的情况下被挂起，但是无论任何情况dispatchWallTime都不会被挂起。

**Comment by 100mango** [comment]
嗯嗯。生命周期的问题。解决了就好。
