### ISSUE TITLE
SwiftTimer.deinit EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)

### ISSUE THREAD

**Issue by laoyur** [100mango/zen#14]
请问在SwiftTimer被释放的时候，报 EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)，大概会是什么问题？

**Comment by laoyur** [comment]
我在停止repeatedTimer时，调用了SwiftTimer.suspend()，然后就导致了EXC_BAD_INSTRUCTION 。
我注释掉了suspend后，就一切ok了。

然后我搜到了以下thread：
http://stackoverflow.com/questions/9572055/dispatch-source-cancel-on-a-suspended-timer-causes-exc-bad-instruction

大概看了下，还不是很明白，但似乎是说停止timer根本无需调用suspend？

**Comment by 100mango** [comment]
麻烦在SwiftTimer的项目处开Issue。然后把完整复现的代码放上来看看。谢谢。
