### ISSUE TITLE
网络相关

### ISSUE THREAD

**Issue by caoyangjiang** [100mango/zen#17]
文章写的都不错，对新手很有帮助。能不能分享一些关于网络的知识。比如，哪些通信机制已经被实现了，哪些需要自己写。我猜想与网站服务器，数据库服务器通信的机制应该已经实现了。 这些无需开发者自己再写。 视频传输或其他的，我不是很清楚是否已经实现了。谢谢🙏

**Comment by 100mango** [comment]
以后有空，整理到这块会写一下。
