### ISSUE TITLE
关于 swift 中的 atomic,苹果官方,给出了一个替代/模拟 atomic 的方案

### ISSUE THREAD

**Issue by yanfeng42** [100mango/zen#18]
> nonatomic,atomic 所有的Swift properties 都是nonatomic。但是我们在线程安全上已经有许多机制,例如NSLock,GCD相关API等。个人推测原因是苹果想把这一个本来就用的很少的特性去掉,线程安全方面交给平时我们用的更多的机制去处理。

苹果官方,给出了一个替代/模拟 atomic 的方案,可以参考下:

[https://github.com/apple/swift-evolution/blob/master/proposals/0030-property-behavior-decls.md#synchronized-property-access](https://github.com/apple/swift-evolution/blob/master/proposals/0030-property-behavior-decls.md#synchronized-property-access)

**Comment by 100mango** [comment]
恩。这个Proposal我有看过，希望未来Swift能够将这个行为加入到语言中。感谢分享。
