### ISSUE TITLE
关于像素重绘问题

### ISSUE THREAD

**Issue by IOSDelpan** [100mango/zen#2]
我一直有研究图形性能方面的东西，关于像素重绘方面，我一直有一个解决不了的问题，为了避免一个像素被过度重绘，我们最好是每个视图都加上背景颜色，特别是文本类的，但在iOS8下，UILabel绘制中文的方式跟iOS8以前的并不一样，即使给UILabel对象添加背景色，也会出现像素重绘问题，我解决的方案是，设置UILabel对像关联的layer的masksToBounds为YES，这样确定是可以解决像素重绘问题，但有些文本会莫名的出现多余的横线，是绘制文本的时候出现的，不知道作者对这块是否有了解。

**Comment by 100mango** [comment]
不好意思，这个问题我没遇到过。不过一般来说，对于UILabel这种常用的系统控件，苹果会帮我们处理好性能问题，因此一般情况可以不需要刻意去改变设置，这样子虽然有可能会对性能有略微损耗，但是避免了我们自己过于Hacking的优化方法造成图像绘制有偏差的情况。

**Comment by IOSDelpan** [comment]
我测试与了解到的情况是，如果不做处理，列表会变得很卡。我有测过微信，微信一样对UILabel作了性能的处理，所以划起来的帧数才能达到55帧左右，如果不处理，大概只能到48帧左右。我测试到，UILabel在iOS8下所关联的图层不再是CALayer，而是UILabelLayer，所以绘制才发生了变化。

**Comment by 100mango** [comment]
感谢提供资讯。在网上没有查找到UILabelLayer的相关信息。有无开启UILabel的opaque。

>  If set to YES, the drawing system treats the view as fully opaque, which allows the drawing system to optimize some drawing operations and improve performance.

**Comment by IOSDelpan** [comment]
有开启，我也试过不开启，但结果是一样的。UILabelLayer是私有的，应该查不到。

**Comment by 100mango** [comment]
这样子。按照官方文档标注，开启后应该就不会造成Blending。如果是iOS8才开始有的话，可能还需要进一步查正一下原因。我在网上帮你查了一下，好像没有关于iOS8下UILabel出现问题的报告。

**Comment by IOSDelpan** [comment]
是这样的，我下了最新的微信，他们一样没作iOS8本文的处理，至于为什么，不清楚。我现在的做法只是，遇到会出现横线的，我就不加背景色，但出现横线的机率并不高

**Comment by 100mango** [comment]
嗯。也可能是苹果官方的bug。可以尝试去StackOverFlow提个问题。希望找到结果之后给大家分享一下。感谢。抱歉没能帮你解决这个问题。

**Comment by IOSDelpan** [comment]
我一会把问题提上去，之前我也写了一些关于图形性能这方面的东西，打算发的，哈哈，你已经发布了，看到就想跟你交流一下。

**Comment by 100mango** [comment]
哈哈。我也是入门选手。以后多多交流。
