### ISSUE TITLE
看了RunLoop的文章，请教一个问题

### ISSUE THREAD

**Issue by weiminghuaa** [100mango/zen#20]
我看到有些event loop的实现，是开启一个线程，使用while做一个死循环，在里面接收状态并处理，使用的是<sys/event.h>里面的kevent，比如这个：https://github.com/douban/DOUAudioStreamer/blob/master/src/DOUAudioEventLoop.m，
并没有使用线程自己的RunLoop。

这个需求能通过RunLoop实现吗，这两个是一个东西吗，我有点蒙圈了。求解！

**Comment by 100mango** [comment]
这个概念是一样的。RunLoop本质上就是一个线程处理任务的模式。
