### ISSUE TITLE
不懂就问，为何我这里增加target报错呢？

### ISSUE THREAD

**Issue by FunnyerFeng** [100mango/zen#22]
<img width="972" alt="截屏2021-07-25 上午3 17 25" src="https://user-images.githubusercontent.com/15104149/126879090-70314979-f4f3-4610-90f3-bed4fba81385.png">

**Comment by 100mango** [comment]
增加target 是没有问题的，应该是语法报错而已。 你可以对照我 demo  中的[package.swift](https://github.com/100mango/zen/blob/master/%E5%9F%BA%E4%BA%8E%20Swift%20%E7%BC%96%E5%86%99%E4%B8%A5%E8%82%83%E8%84%9A%E6%9C%AC%E5%B7%A5%E5%85%B7/script/Package.swift)  看一下差异。
我估计是你定义的 package.swift 的swift tool version 没有声明为 5.4。 executableTarget 这个API 要 5.4 之后才能使用。
