### ISSUE TITLE
非常感谢！

### ISSUE THREAD

**Issue by iTofu** [100mango/zen#8]
之前对Swift只停留在基本了解，一直在犹豫要不要转Swifter，现在看来，Swift这条船我还是上吧！
很感谢作者的这些[Tip](https://github.com/100mango/zen/blob/master/Swift%E5%AD%A6%E4%B9%A0%EF%BC%9A%E4%BB%8EObjective-C%E5%88%B0Swift/Swift%E5%AD%A6%E4%B9%A0%EF%BC%9A%E4%BB%8EObjective-C%E5%88%B0Swift.md)！能少走很多弯路！

**Comment by 100mango** [comment]
感谢支持！共同学习进步。
